# Site settings
title: M-x doctor RET
email: bzg+emacs@bzg.fr
description: Everybody needs a good Emacs doctor.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://emacs-doctor.com" # the base hostname & protocol for your site
twitter_username: bzg2
github_username:  bzg
permalink: /:title.html

# Build settings
markdown: kramdown
