# Site settings
title: M-x doctor RET
email: bzg+emacsREMOVEME@bzg.fr
description: Everybody needs a good Emacs doctor.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.emacs-doctor.com" # the base hostname & protocol for your site
twitter_username: bzg2
github_username:  bzg
permalink: /:title.html
destination: docs/

# Build settings
markdown: kramdown
